FROM python:3-slim
WORKDIR /usr/src/app
COPY http.reqs.txt amqp_req.txt ./
RUN python -m pip install --no-cache-dir -r http.reqs.txt -r amqp_req.txt
COPY ./redeemRewards.py ./invokes.py ./amqp_setup.py ./
CMD [ "python", "./redeemRewards.py" ]