FROM python:3-slim
WORKDIR /usr/src/app
COPY amqp_req.txt ./
RUN python -m pip install --no-cache-dir -r amqp_req.txt
COPY ./sendAdvert.py ./amqp_setup.py ./invokes.py ./
CMD [ "python", "./sendAdvert.py" ]