FROM python:3-slim
WORKDIR /usr/src/app
COPY aggregateData_req.txt ./
RUN python -m pip install --no-cache-dir -r aggregateData_req.txt
COPY ./aggregateData.py ./invokes.py ./
CMD [ "python", "./aggregateData.py" ]